kind: Kustomization

helmCharts:
- name: aws-mountpoint-s3-csi-driver
  repo: https://awslabs.github.io/mountpoint-s3-csi-driver
  version: 2.3.0
  releaseName: aws-mountpoint-s3-csi-driver
  namespace: kube-system
  # valuesFile: values.yaml
  valuesInline:
    mountpointPod:
      namespace: csi-mountpoint-s3
    supportLegacySystemDMounts: false

resources:
- s3-credentials.yaml